# Generated by Django 3.2.8 on 2021-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='category',
            field=models.CharField(default='not predicted yet', max_length=100),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='predicted',
            field=models.BooleanField(default=False),
        ),
    ]
